source 'https://github.com/CocoaPods/Specs.git'
platform :ios, 9.0
use_frameworks!

target 'Logsene_Example' do
  pod 'Logsene', :path => '../'
  pod 'CocoaLumberjack/Swift'

	target 'Logsene_Tests' do
	  inherit! :search_paths

	  pod 'Quick'
	  pod 'Nimble'
	end
end
